language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
  chrome: stable

env:
  -DJANGO=2.1.7 DB=postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE apexselftaught;" -U postgres
  - python manage.py makemigrations
  - python manage.py migrate_schemas

script:
  - coverage run -m pytest --reuse-db --no-migrations -vv && coverage report -m

after_success:
  - bash <(curl -s https://codecov.io/bash)